name: evomoblie_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  auto_route: 11.1.0
  build_runner: ^2.10.5
  flutter_svg: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: 10.4.0


flutter:
  uses-material-design: true
  assets:
    - lib/presentation/assets/icons/
