name: evomoblie_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  auto_route: 11.1.0
  build_runner: ^2.10.5
  flutter_svg: ^2.2.3
  flutter_bloc: ^9.1.1
  group_button: ^5.3.4
  calendar_date_picker2: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  import_sorter: ^4.6.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: 10.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/assets/icons/
import_sorter:
  emojis: false
  comments: false
